"""Generated root CLI help; see scripts/generate_cli_help.py."""

ROOT_HELP = (
    "usage: sat [-h] [--version]\n           [--progress-visibility {compa"
    "ct,standard,detailed}]\n           [--progress-display {auto,live,log"
    "}]\n           [--progress-color {auto,always,never}]\n           {uni"
    "nstall,version,update,channel,cleanup,_managed-install,_managed-stat"
    "e-compatibility,_managed-image-transition,configure,validate-handoff"
    ",validate-task-brief,validate-artifact,validate-config,list-teams,pr"
    "epare-benchmark,preflight,run}\n           ...\n\nBuild a confirmed sof"
    "tware request with a guided Agent team, or use an\nexplicit subcomman"
    "d for configuration and evaluation.\n\npositional arguments:\n  {uninst"
    "all,version,update,channel,cleanup,_managed-install,_managed-state-c"
    "ompatibility,_managed-image-transition,configure,validate-handoff,va"
    "lidate-task-brief,validate-artifact,validate-config,list-teams,prepa"
    "re-benchmark,preflight,run}\n    uninstall           Remove the owned"
    " installation; preserve saved data by\n                        defaul"
    "t.\n    version             Show detailed, non-networked release and "
    "provenance\n                        information.\n    update          "
    "    Check or apply an update from the active managed\n               "
    "         channel.\n    channel             Inspect or explicitly swit"
    "ch the managed release\n                        channel.\n    cleanup "
    "            Inspect or reclaim only proven orphaned SAT runtime\n    "
    "                    resources.\n    _managed-install    ==SUPPRESS==\n"
    "    _managed-state-compatibility\n                        ==SUPPRESS="
    "=\n    _managed-image-transition\n                        ==SUPPRESS=="
    "\n    configure           Create or replace secret-free model and adv"
    "anced run\n                        defaults.\n    validate-handoff    "
    "Validate a persisted handoff envelope.\n    validate-task-brief\n     "
    "                   Validate a clarified task brief.\n    validate-art"
    "ifact   Validate the structure of a persisted phase artifact.\n    va"
    "lidate-config     Validate all checked-in team, runtime, policy, and"
    "\n                        benchmark config.\n    list-teams          L"
    "ist versioned experimental team configurations.\n    prepare-benchmar"
    "k   Create the fixed task-manager seed as a clean Git\n              "
    "          repository.\n    preflight           Check the source repos"
    "itory, OpenClaw configuration,\n                        and sandbox i"
    "mage without a model call.\n    run                 Execute the compl"
    "ete function-specialized Phase 1\n                        workflow.\n\n"
    "options:\n  -h, --help            show this help message and exit\n  -"
    "-version             Show the installed SAT release and exact source"
    "\n                        identity, then exit.\n  --progress-visibilit"
    "y {compact,standard,detailed}\n                        Override progr"
    "ess detail for this guided run only.\n  --progress-display {auto,live"
    ",log}\n                        Override automatic, live, or append-on"
    "ly progress for\n                        this run only.\n  --progress-"
    "color {auto,always,never}\n                        Override automatic"
    ", preferred, or disabled color for\n                        this run "
    "only.\n"
)
