"""Generated root CLI help; see scripts/generate_cli_help.py."""

ROOT_HELP = (
    "usage: sat [-h] [--version]\n           [--progress-visibility {compa"
    "ct,standard,detailed}]\n           [--progress-display {auto,live,log"
    "}]\n           [--progress-color {auto,always,never}]\n           {ver"
    "sion,update,channel,cleanup,_managed-install,_managed-state-compatib"
    "ility,_managed-image-transition,configure,validate-handoff,validate-"
    "task-brief,validate-artifact,validate-config,list-teams,prepare-benc"
    "hmark,preflight,run}\n           ...\n\nBuild a confirmed software requ"
    "est with a guided Agent team, or use an\nexplicit subcommand for conf"
    "iguration and evaluation.\n\npositional arguments:\n  {version,update,c"
    "hannel,cleanup,_managed-install,_managed-state-compatibility,_manage"
    "d-image-transition,configure,validate-handoff,validate-task-brief,va"
    "lidate-artifact,validate-config,list-teams,prepare-benchmark,preflig"
    "ht,run}\n    version             Show detailed, non-networked release"
    " and provenance\n                        information.\n    update     "
    "         Check or apply an update from the active managed\n          "
    "              channel.\n    channel             Inspect or explicitly"
    " switch the managed release\n                        channel.\n    cle"
    "anup             Inspect or reclaim only proven orphaned SAT runtime"
    "\n                        resources.\n    _managed-install    ==SUPPRE"
    "SS==\n    _managed-state-compatibility\n                        ==SUPP"
    "RESS==\n    _managed-image-transition\n                        ==SUPPR"
    "ESS==\n    configure           Create or replace secret-free model an"
    "d advanced run\n                        defaults.\n    validate-handof"
    "f    Validate a persisted handoff envelope.\n    validate-task-brief\n"
    "                        Validate a clarified task brief.\n    validat"
    "e-artifact   Validate the structure of a persisted phase artifact.\n "
    "   validate-config     Validate all checked-in team, runtime, policy"
    ", and\n                        benchmark config.\n    list-teams      "
    "    List versioned experimental team configurations.\n    prepare-ben"
    "chmark   Create the fixed task-manager seed as a clean Git\n         "
    "               repository.\n    preflight           Check the source "
    "repository, OpenClaw configuration,\n                        and sand"
    "box image without a model call.\n    run                 Execute the "
    "complete function-specialized Phase 1\n                        workfl"
    "ow.\n\noptions:\n  -h, --help            show this help message and exi"
    "t\n  --version             Show the installed SAT release and exact s"
    "ource\n                        identity, then exit.\n  --progress-visi"
    "bility {compact,standard,detailed}\n                        Override "
    "progress detail for this guided run only.\n  --progress-display {auto"
    ",live,log}\n                        Override automatic, live, or appe"
    "nd-only progress for\n                        this run only.\n  --prog"
    "ress-color {auto,always,never}\n                        Override auto"
    "matic, preferred, or disabled color for\n                        this"
    " run only.\n"
)
